vim.opt.clipboard = 'unnamedplus' -- allows neovim to access the system clipboard
vim.opt.cursorline = true
vim.opt.expandtab = true          -- convert tabs to spaces
vim.opt.hlsearch = true           -- highlight all matches on previous search pattern
vim.opt.ignorecase = true         -- ignore case in search patterns
vim.opt.inccommand = 'split'
vim.opt.incsearch = true
vim.opt.iskeyword:append('-')
vim.opt.number = true -- set numbered lines
vim.opt.relativenumber = true
vim.opt.ruler = false
vim.opt.scrolloff = 15
vim.opt.shiftwidth = 4
vim.opt.showmode = false   -- we don't need to see things like -- INSERT -- anymore
vim.opt.showtabline = 0    -- always show tabs
vim.opt.signcolumn = 'no'  -- always show the sign column, otherwise it would shift the text each time
vim.opt.smartcase = true   -- smart case
vim.opt.smartindent = true -- make indenting smarter again
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.tabstop = 4
vim.opt.termguicolors = true -- set term gui colors (most terminals support this)
vim.opt.undofile = true      -- enable persistent undo
vim.opt.cmdheight = 0
