return {
	{
		{ 'nvim-lua/plenary.nvim' },
		{ 'kyazdani42/nvim-web-devicons' },
		{ 'moll/vim-bbye' },
		{ 'lukas-reineke/indent-blankline.nvim' },
		{ 'folke/neodev.nvim', config = true },
		{ 'roobert/tailwindcss-colorizer-cmp.nvim', config = true },
		{ 'simrat39/rust-tools.nvim', config = true },
		{ 'neovim/nvim-lspconfig' },
		{ 'williamboman/nvim-lsp-installer' },
		{ 'williamboman/mason.nvim' },
		{ 'williamboman/mason-lspconfig.nvim' },
		{ 'jose-elias-alvarez/null-ls.nvim' },
		{ 'https://git.sr.ht/~whynothugo/lsp_lines.nvim' },
		{ 'lvimuser/lsp-inlayhints.nvim' },
		{ 'lewis6991/gitsigns.nvim' },
		{ 'gpanders/editorconfig.nvim' },
		{ 'stevearc/dressing.nvim', config = true },
		{ 'kevinhwang91/nvim-bqf' },
		{ 'NTBBloodbath/rest.nvim' },
		{ 'christoomey/vim-tmux-navigator' },
		{ 'NvChad/nvim-colorizer.lua', opts = { user_default_options = { tailwind = true } } },
	},
}
